config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users,
             path: "",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               edit: "profile",
               sign_up: "registration",
             },
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  resources :users, only: :show

  scope module: :current_user do
    post  "verify_phone_number"
    patch "update_phone_number"
  end

  namespace :open_hours do
    resources :week_days, only: %i[create update destroy]
    resources :special_days, only: %i[create update destroy]
  end

  resources :reservations, only: :index

  resources :rooms, except: [:edit] do
    member do
      get "preload"
      get "preview"
      get "availability"
    end

    resources :photos, only: %i[create destroy]
    resources :reservations, only: :create

    # resources :calendars
  end

  resources :guest_reviews, only: %i[create destroy]
  resources :host_reviews, only: %i[create destroy]
  resources :subscriptions, only: %i[index new create]

  get "search" => "pages#search"
  get "why" => "pages#why"
  get "how-it-works" => "pages#how_it_works"
  get "faq" => "pages#faq"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "terms" => "pages#terms"

  # resources :revenues, only: [:index]

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

  resources :messages, only: :destroy

  # get '/host_calendar' => "calendars#host"

  get "/notification_settings" => "settings#edit"
  post "/notification_settings" => "settings#update"

  get "/notifications" => "notifications#index"

  mount ActionCable.server => "/cable"

  # Supplier
  namespace :suppliers do
    resources :reservations, only: :index do
      member do
        post :approve
        post :decline
      end
    end

    resources :rooms, only: %i[index new create update] do
      member do
        get :description
        get :amenities
        get :pricing
        get :location
        get "open_hours"
        get :photo_upload
      end
    end

    get :dashboard, to: "dashboard#index"
  end

  # Admin Panel
  namespace :panel do
    root "users#index"

    get    "/login"  => "sessions#new"
    post   "/login"  => "sessions#create"
    delete "/logout" => "sessions#destroy"

    resources :admins, only: %i[index new create edit update destroy]
    resources :featured_clinics, only: [:index]
    resources :clinics, only: [:update]
    resources :plans, only: %i[index edit update]

    resources :users, only: [:index] do
      resources :clinics, only: [:index]
    end
  end

  # Errors
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/controllers/panel/admins_controller.rb
class Panel::AdminsController < PanelController
  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def create
    email = params[:admin][:email]
    password = Devise.friendly_token.first(8)

    @admin = Admin.new(email: email, password: password)

    if @admin.save
      flash[:success] = "Usuario <strong>#{@admin.email}</strong> creado exitosamente."
      PanelMailer.welcome(@admin.email, password).deliver_later
    end
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    @admin = Admin.find(params[:id])

    if @admin.update(admin_params)
      flash[:success] = "Contraseña actualizada exitosamente."
    end

    render :create
  end

  def destroy
    admin = Admin.find(params[:id])
    admin.destroy

    redirect_to action: "index"
  end

  private
  def admin_params
    params.require(:admin).permit(:password, :password_confirmation)
  end
end

app/controllers/panel/clinics_controller.rb
class Panel::ClinicsController < PanelController
  def index
    @user = User.find(params[:user_id])
  end

  def update
    @room = Room.find(params[:id])

    if @room.update(clinic_params)
      render json: { status: 200 }
    else
      render json: { error: @room.errors.full_messages.first }
    end
  end

  private

  def clinic_params
    params.
      require(:clinic).
      permit(:approved, :active, :featured, :search_priority, :featured_order)
  end
end

app/controllers/panel/featured_clinics_controller.rb
class Panel::FeaturedClinicsController < PanelController
  def index
    @rooms = Room.featured
  end
end

app/controllers/panel/plans_controller.rb
class Panel::PlansController < PanelController
  def index
    @plans = Plan.all.order(id: :ASC)
  end

  def edit
    @plan = Plan.find(params[:id])
  end


  def update
    @plan = Plan.find(params[:id])

    if @plan.update(plan_params)
      flash[:success] = "Plan actualizado exitosamente."
    end
  end

  private
  def plan_params
    params.require(:plan)
          .permit(:name, :price_monthly, :price_semiannual, :price_annual)
  end
end

app/controllers/panel/sessions_controller.rb
class Panel::SessionsController < PanelController
  skip_before_action :authenticate_admin!

  def new
    @admin = Admin.new
  end

  def create
    admin = Admin.find_by(email: params[:admin][:email].downcase)

    if admin && admin.authenticate(params[:admin][:password])
      session[:admin_id] = admin.id.to_s

      redirect_to panel_root_path
    else
      flash.now[:error] = "Invalid e-mail or password."
      render :new
    end
  end

  def destroy
    session.delete(:admin_id)

    redirect_to panel_login_path
  end
end

app/controllers/panel/users_controller.rb
class Panel::UsersController < PanelController
  def index
    @users = User.all
  end
end

app/controllers/panel_controller.rb
class PanelController < ActionController::Base
  layout 'panel'

  protect_from_forgery with: :exception
  before_action :authenticate_admin!
  helper_method :current_admin

  def current_admin
    @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end

  def authenticate_admin!
    redirect_to panel_login_path if current_admin.nil?
  end
end

app/helpers/panel_helper.rb
module PanelHelper
  def status_icon_for(flag)
    icon = flag ? "check" : "times"

    content_tag(:i, "", class: "fa fa-#{icon}-circle-o on")
  end

  def human_boolean(flag)
    flag ? "Yes" : "No"
  end
end

app/views/panel/admins/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3 class="modal-title">
        Change password
      </h3>
    </div>

    <div class="modal-body">
      <%= form_for admin, url: panel_admin_path(admin), remote: true do |f| %>
        <div class="admin-error alert-danger" style="display: none;"></div>
        <div class="form-group">
          <%= f.label :password, class: "control-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, class: "control-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="user-modal-footer center">
          <%= f.submit " Change ", class: "btn btn-normal user-save center" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/panel/admins/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3 class="modal-title">
        Add administrator
      </h3>
    </div>

    <div class="modal-body">
      <%= form_for admin, url: panel_admins_path, remote: true do |f| %>
        <div class="subscription-error alert-danger" style="display: none;"></div>
        <div class="form-group">
          <%= f.label :email, class: "control-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="user-modal-footer center">
          <%= f.submit " Add ", class: "btn btn-normal user-save center" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/panel/admins/create.js.erb
$('div.admin-error').html('');
$('div.admin-error').css('display', 'none');

<% if @admin.errors.any? %>
  $('div.admin-error').html('<%= @admin.errors.full_messages.first %>');
  $('div.admin-error').css('display', 'block');

<% else %>
  $('#new-admin-modal').modal('hide');
  location.reload();
<% end %>

app/views/panel/admins/edit.js.erb
$("#new-admin-modal").html("<%= j(render 'edit', admin: @admin) %>");
$('#new-admin-modal').modal("show");

app/views/panel/admins/index.html.erb
<% provide(:title, "Administrators") %>

<div id="messages">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message.html_safe %></div>
  <% end %>
</div>

<div class="row">
  <div class="col-md-6">
    <% @admins.each do |admin| %>
      <div class="row admin-row">
        <div class="col-md-6">
          <span class="admin-text-box"><%= admin.email %></span>
        </div>
        <div class="col-md-6">
          <%= link_to panel_admin_path(admin), class: "pull-right",
              data: { confirm: 'Esta acción no se puede deshacer, ¿está seguro?' },
              method: :delete do %>
            <i class="fa fa-trash admin-text-box"></i>
          <% end %>

          <% if current_admin.email == admin.email %>
            <%= link_to edit_panel_admin_path(admin), class: "pull-right", remote: true do %>
              <i class="fa fa-pencil admin-text-box"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

    <div>
      <%= link_to "Add administrator", new_panel_admin_path, class: "pull-right", remote: true %>
    </div>
  </div>
</div>

<div id="new-admin-modal" tabindex="-1" role="dialog" class="modal fade"></div>

<script type="text/javascript">
  $(document).ready(function() {
    setTimeout(function() {
      $('#messages').animate({ height: 0, opacity: 0 }, 'slow');
    }, 3500);
  });
</script>

app/views/panel/admins/new.js.erb
$("#new-admin-modal").html("<%= j(render 'new', admin: @admin) %>");
$('#new-admin-modal').modal("show");