config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users,
             path: "",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               edit: "profile",
               sign_up: "registration",
             },
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  resources :users, only: :show

  scope module: :current_user do
    post  "verify_phone_number"
    patch "update_phone_number"
  end

  namespace :open_hours do
    resources :week_days, only: %i[create update destroy]
    resources :special_days, only: %i[create update destroy]
  end

  resources :reservations, only: :index

  resources :rooms, except: [:edit] do
    member do
      get "preload"
      get "preview"
      get "availability"
    end

    resources :photos, only: %i[create destroy]
    resources :reservations, only: :create

    # resources :calendars
  end

  resources :guest_reviews, only: %i[create destroy]
  resources :host_reviews, only: %i[create destroy]
  resources :subscriptions, only: %i[index new create]

  get "search" => "pages#search"
  get "why" => "pages#why"
  get "how-it-works" => "pages#how_it_works"
  get "faq" => "pages#faq"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "terms" => "pages#terms"

  # resources :revenues, only: [:index]

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

  resources :messages, only: :destroy

  # get '/host_calendar' => "calendars#host"

  get "/notification_settings" => "settings#edit"
  post "/notification_settings" => "settings#update"

  get "/notifications" => "notifications#index"

  mount ActionCable.server => "/cable"

  # Supplier
  namespace :suppliers do
    resources :reservations, only: :index do
      member do
        post :approve
        post :decline
      end
    end

    resources :rooms, only: %i[index new create update] do
      member do
        get :description
        get :amenities
        get :pricing
        get :location
        get "open_hours"
        get :photo_upload
      end
    end

    get :dashboard, to: "dashboard#index"
  end

  # Admin Panel
  namespace :panel do
    root "users#index"

    get    "/login"  => "sessions#new"
    post   "/login"  => "sessions#create"
    delete "/logout" => "sessions#destroy"

    resources :admins, only: %i[index new create edit update destroy]
    resources :featured_clinics, only: [:index]
    resources :clinics, only: [:update]
    resources :plans, only: %i[index edit update]

    resources :users, only: [:index] do
      resources :clinics, only: [:index]
    end
  end

  # Errors
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="navbar-default footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <h4>Get Started</h4>
        <ul>
          <li><%= link_to "Book an appointment", search_path(search: "Quito, Ecuador") %></li>
          <li><%= link_to "Increase your clinic's revenue", subscriptions_path %></li>
        </ul>
      </div>
      <div class="col-xs-4">
        <h4>Learn More</h4>
        <ul>
          <li><%= link_to "Why StrollnSmile?", why_path %></li>
          <li><%= link_to "How it works?", how_it_works_path %></li>
          <li><%= link_to "Pricing", subscriptions_path %></li>
        </ul>
      </div>
      <div class="col-xs-4">
        <i class="fa fa-instagram icon-link fa-2x" aria-hidden="true" data-url="https://www.instagram.com/strollnsmile/"></i>
        <i class="fa fa-facebook icon-link fa-2x" aria-hidden="true" data-url="https://www.facebook.com/strollnsmile/"></i>
        <i class="fa fa-twitter icon-link fa-2x" aria-hidden="true" data-url="https://twitter.com/strollnsmile"></i>
        <p><%= link_to "Frequently Asked Questions", faq_path  %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <ul class="list-inline">
          <li class="copyright"><i class="fa fa-copyright"></i> StrollnSmile 2020</li>
          <li><%= link_to "About", why_path %></li>
          <li><%= link_to "Contact", "mailto:strollnsmile@gmail.com" %></li>
          <li><%= link_to "Privacy", privacy_path %></li>
          <li><%= link_to "Terms", terms_path %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<script>
$('.icon-link').on('click', function() {
  window.open($(this).attr("data-url"))
});
</script>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" style ="margin-bottom: 0px">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo2.jpg", style: "height:100%; width:auto;"),
          root_path, class: "navbar-brand", style: "padding: 8px 0px 0px" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: "navbar-form navbar-left", "data-behavior": "single-field-form", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :location, params[:location], id: 'search-box', placeholder: "e.g. Quito, Ecuador",
                             class: "form-control", "data-behavior": "geocomplete" %>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <button class="btn btn-form btn-small">
            <%= link_to "Become a Dental Supplier", new_suppliers_room_path, style: "color: white; text-decoration: none;" %>
          </button>
        </li>

        <% if (!user_signed_in?) %>
          <li class="menu-item"><%= link_to "Login", new_user_session_path %></li>
          <li class="menu-item"><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li>
            <%= link_to notifications_path do %>
              <i class="fa fa-bell fa-2x icon-babu"></i>
              <span class="badge" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                        aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Reservations", reservations_path %></li>
              <li><%= link_to "My Conversations", conversations_path %></li>
              <% if current_user.supplier? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Manage Clinics", suppliers_dashboard_path %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_rooms_list.html.erb
<% rooms.each do |room| %>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag room.cover_photo(:medium) %>
      </div>
      <div class="panel-body search-result-box">
        <%= link_to room.name, room_path(room, date: defined?(date) ? date : nil) %><br/>
        $<%= room.price %>
        <div id="star_<%= room.id %>"></div> <%= pluralize(room.guest_reviews.count, "review") %>

        <% if action_name == "search" %>
          <hr>
          <div>Open Hours</div>
          <span class="bottom-text"><%= room.open_hours %></span>
          <hr>
          <div>Availability on <b><%= @search.date %></b></div>
          <span class="bottom-text"><%= room.availability_on(@search.date).join(", ") %></span>
        <% end %>
      </div>
    </div>
  </div>

  <script>
    $('#star_<%= room.id %>').raty({
      path: '/images',
      readOnly: true,
      score: <%= room.average_rating %>
    });
  </script>
<% end %>

app/views/shared/_suppliers_navbar.html.erb
<nav class="navbar navbar-default" style="background-color: #565A5C">
  <div class="container">
    <ul class="nav navbar-nav">
      <%= dashboard_menu_link("Dashboard", suppliers_dashboard_path) %>
      <%= dashboard_menu_link("Listings", suppliers_rooms_path) %>
      <%= dashboard_menu_link("Reservations", suppliers_reservations_path) %>
    </ul>
  </div>
</nav>

app/views/shared/_users_navbar.html.erb
<nav class="navbar navbar-default" style="background-color: #565A5C">
  <div class="container">
    <ul class="nav navbar-nav">
      <%= dashboard_menu_link("My Reservations", reservations_path) %>
      <%= dashboard_menu_link("My Conversations", conversations_path) %>
    </ul>
  </div>
</nav>