config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users,
             path: "",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               edit: "profile",
               sign_up: "registration",
             },
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  resources :users, only: :show

  scope module: :current_user do
    post  "verify_phone_number"
    patch "update_phone_number"
  end

  namespace :open_hours do
    resources :week_days, only: %i[create update destroy]
    resources :special_days, only: %i[create update destroy]
  end

  resources :reservations, only: :index

  resources :rooms, except: [:edit] do
    member do
      get "preload"
      get "preview"
      get "availability"
    end

    resources :photos, only: %i[create destroy]
    resources :reservations, only: :create

    # resources :calendars
  end

  resources :guest_reviews, only: %i[create destroy]
  resources :host_reviews, only: %i[create destroy]
  resources :subscriptions, only: %i[index new create]

  get "search" => "pages#search"
  get "why" => "pages#why"
  get "how-it-works" => "pages#how_it_works"
  get "faq" => "pages#faq"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "terms" => "pages#terms"

  # resources :revenues, only: [:index]

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

  resources :messages, only: :destroy

  # get '/host_calendar' => "calendars#host"

  get "/notification_settings" => "settings#edit"
  post "/notification_settings" => "settings#update"

  get "/notifications" => "notifications#index"

  mount ActionCable.server => "/cable"

  # Supplier
  namespace :suppliers do
    resources :reservations, only: :index do
      member do
        post :approve
        post :decline
      end
    end

    resources :rooms, only: %i[index new create update] do
      member do
        get :description
        get :amenities
        get :pricing
        get :location
        get "open_hours"
        get :photo_upload
      end
    end

    get :dashboard, to: "dashboard#index"
  end

  # Admin Panel
  namespace :panel do
    root "users#index"

    get    "/login"  => "sessions#new"
    post   "/login"  => "sessions#create"
    delete "/logout" => "sessions#destroy"

    resources :admins, only: %i[index new create edit update destroy]
    resources :featured_clinics, only: [:index]
    resources :clinics, only: [:update]
    resources :plans, only: %i[index edit update]

    resources :users, only: [:index] do
      resources :clinics, only: [:index]
    end
  end

  # Errors
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  default_scope { order(datetime: :ASC) }

  enum status: { waiting: 0, approved: 1, declined: 2 }

  belongs_to :user
  belongs_to :room

  validate :availability, on: :create

  def self.on(date)
    where(datetime: date.beginning_of_day..date.end_of_day)
  end

  def self.current_week_revenue(user)
    joins(:room).
      where(status: 1, rooms: { user_id: user.id }).
      where(arel_table[:updated_at].gteq(1.week.ago.round)).
      order(updated_at: :asc)
  end

  def save_and_notify
    if save
      create_notification

      self
    else
      false
    end
  end

  def time
    datetime.strftime("%H:%M")
  end

  private

  def availability
    if Reservation.find_by(room_id: room_id, datetime: datetime).present?
      errors.add(:datetime, "not available for booking")
    end
  end

  def create_notification
    Notification.new(
      content: "New Booking from #{user.fullname}",
      user_id: room.user_id,
      url: Rails.application.routes.url_helpers.suppliers_reservations_path,
    ).save_and_broadcast
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = current_user.reservations
  end

  def create
    room = Room.find(params[:room_id])

    @reservation = Reservation.new(
      datetime: datetime,
      price: room.price,
      user_id: current_user.id,
      room_id: room.id,
    )

    if @reservation.save_and_notify
      flash[:notice] = "Request sent successfully!"
    else
      flash[:alert] = @reservation.errors.full_messages.first
    end

    redirect_to room
  end

  private

  def datetime
    date_array = Date.parse(reservation_params[:datetime]).to_s.split("-")
    time_array = reservation_params[:time].split(":")

    Time.new(*(date_array + time_array))
  end

  def reservation_params
    params.require(:reservation).permit(:datetime, :time)
  end
end

app/controllers/suppliers/dashboard_controller.rb
module Suppliers
  class DashboardController < SuppliersController
    def index
      @rooms = current_user.rooms
    end
  end
end

app/controllers/suppliers/reservations_controller.rb
module Suppliers
  class ReservationsController < SuppliersController
    before_action :set_reservation, except: :index

    def index
      @reservations = current_user.rooms_reservations
    end

    def approve
      @reservation.approved!

      NotifyReservationApproval.call(@reservation)
      flash[:notice] = "Reservation created successfully!"

      redirect_to suppliers_reservations_path
    end

    def decline
      @reservation.declined!

      redirect_to suppliers_reservations_path
    end

    private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end
  end
end

app/controllers/suppliers/rooms_controller.rb
module Suppliers
  class RoomsController < SuppliersController
    skip_before_action :authorize_supplier, only: %i[new create]

    before_action :set_room, except: %i[index new create]
    before_action :authorize_user!, except: %i[index new create]

    def index
      @rooms = current_user.rooms
    end

    def new
      @room = current_user.rooms.build
    end

    def create
      @room = current_user.rooms.build(room_params)

      if @room.save
        redirect_to open_hours_suppliers_room_path(@room), notice: "Saved..."
      else
        flash[:alert] = @room.errors.full_messages.first

        render :new
      end
    end

    def update
      if @room.update(room_params)
        flash[:notice] = "Saved..."
      else
        flash[:alert] = @room.errors.full_messages.first
      end

      redirect_back(fallback_location: root_path)
    end

    def description; end

    def amenities; end

    def pricing; end

    def location; end

    def open_hours; end

    def photo_upload; end

    private

    def set_room
      @room = Room.find(params[:id])
    end

    def authorize_user!
      if current_user.id != @room.user_id
        redirect_to root_path, alert: "You don't have permission"
      end
    end

    def room_params
      params.
        require(:room).
        permit(
          :name, :address, :summary, :stations, :price, :active,
          :available_procedures, :open_hours, :practitioners, :has_lobby,
          :has_xrays, :has_heating, :has_internet, :appointment_duration,
          payment_methods: [], open_hours_week_days: [],
          open_hours_special_days: []
        )
    end
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_supplier

  private

  def authorize_supplier
    redirect_to root_path unless current_user.supplier?
  end
end

app/views/suppliers/reservations/index.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Reservations
      </div>
      <div class="panel-body">

        <% @reservations.each do |reservation| %>
          <div class="row">
            <div class="col-md-2">
              <%= reservation.datetime.strftime('%v') %>
              <%= reservation.datetime.strftime('%R') %>
              <p><%= reservation.status %></p>
              <div class="form-inline">
                <% if reservation.waiting? %>
                  <%= link_to approve_suppliers_reservation_path(reservation), method: :post do %>
                    <i class="fa fa-thumbs-up fa-lg"></i>
                  <% end %> |
                  <%= link_to decline_suppliers_reservation_path(reservation), method: :post do %>
                    <i class="fa fa-thumbs-down fa-lg"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="col-md-2">
              <%= link_to room_path(reservation.room) do %>
                <%= image_tag reservation.room.cover_photo(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-5">
              <%= link_to reservation.room.name, room_path(reservation.room) %><br/><br/>
              <span>
                <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %>
                <%= link_to reservation.user.fullname, user_path(reservation.user) %>

                <% if current_user.id != reservation.user_id %>
                  (<%= link_to "send message", conversations_path(sender_id: current_user.id, recipient_id: reservation.user_id),
                   method: :post %>)
                 <% end %>
              </span>
            </div>
            <div class="col-md-3 text-right">
              <%= render "reviews/host_form", reservation: reservation if reservation.approved? %>
            </div>
          </div>
          <hr/>
        <% end %>

      </div>
    </div>
  </div>
</div>