config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users,
             path: "",
             path_names: {
               sign_in: "login",
               sign_out: "logout",
               edit: "profile",
               sign_up: "registration",
             },
             controllers: {
               omniauth_callbacks: "omniauth_callbacks",
               registrations: "registrations",
             }

  resources :users, only: :show

  scope module: :current_user do
    post  "verify_phone_number"
    patch "update_phone_number"
  end

  namespace :open_hours do
    resources :week_days, only: %i[create update destroy]
    resources :special_days, only: %i[create update destroy]
  end

  resources :reservations, only: :index

  resources :rooms, except: [:edit] do
    member do
      get "preload"
      get "preview"
      get "availability"
    end

    resources :photos, only: %i[create destroy]
    resources :reservations, only: :create

    # resources :calendars
  end

  resources :guest_reviews, only: %i[create destroy]
  resources :host_reviews, only: %i[create destroy]
  resources :subscriptions, only: %i[index new create]

  get "search" => "pages#search"
  get "why" => "pages#why"
  get "how-it-works" => "pages#how_it_works"
  get "faq" => "pages#faq"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "terms" => "pages#terms"

  # resources :revenues, only: [:index]

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

  resources :messages, only: :destroy

  # get '/host_calendar' => "calendars#host"

  get "/notification_settings" => "settings#edit"
  post "/notification_settings" => "settings#update"

  get "/notifications" => "notifications#index"

  mount ActionCable.server => "/cable"

  # Supplier
  namespace :suppliers do
    resources :reservations, only: :index do
      member do
        post :approve
        post :decline
      end
    end

    resources :rooms, only: %i[index new create update] do
      member do
        get :description
        get :amenities
        get :pricing
        get :location
        get "open_hours"
        get :photo_upload
      end
    end

    get :dashboard, to: "dashboard#index"
  end

  # Admin Panel
  namespace :panel do
    root "users#index"

    get    "/login"  => "sessions#new"
    post   "/login"  => "sessions#create"
    delete "/logout" => "sessions#destroy"

    resources :admins, only: %i[index new create edit update destroy]
    resources :featured_clinics, only: [:index]
    resources :clinics, only: [:update]
    resources :plans, only: %i[index edit update]

    resources :users, only: [:index] do
      resources :clinics, only: [:index]
    end
  end

  # Errors
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/models/room.rb
class Room < ApplicationRecord
  ACCEPTED_PAYMENT_METHODS = %w(Cash PayPal MasterCard Visa DinersClub).freeze
  DEAFULT_SEARCH_RADIUS    = 10

  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :guest_reviews, dependent: :destroy
  has_many :calendars, dependent: :destroy

  has_many :open_hours_week_days,
           class_name: "OpenHours::WeekDay",
           dependent: :destroy

  has_many :open_hours_special_days,
           class_name: "OpenHours::SpecialDay",
           dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :summary, presence: true
  validates :has_lobby, inclusion: { in: [true, false] }
  validates :has_xrays, inclusion: { in: [true, false] }
  validates :has_heating, inclusion: { in: [true, false] }
  validates :has_internet, inclusion: { in: [true, false] }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :practitioners, numericality: { greater_than: 0 }
  validates :stations, numericality: { greater_than: 0 }
  validates :open_hours, presence: true
  validates :active, inclusion: { in: [true, false] }

  validate :accepted_payment_methods

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  before_save :deactivate, unless: :approved?

  scope :active,      -> { where(active: true) }
  scope :prioritized, -> { order(search_priority: :ASC) }
  scope :featured,    -> { where(featured: true).order(featured_order: :ASC) }

  def self.near_by(location, radius = 10)
    active.near(location, radius, order: "distance")
  end

  def self.available_on(date)
    select { |room| room.available_on?(date) }
  end

  def self.maximum_price
    maximum(:price).to_i
  end

  def self.minimum_price
    minimum(:price).to_i
  end

  def open_hours_by_week_day
    open_hours = open_hours_week_days.by_day

    OpenHours::WeekDay.week_days.each_key.with_object({}) do |day, result|
      result[day] = open_hours[day].presence || []
    end
  end

  def open_hours_by_special_day
    open_hours_special_days.order(:month, :day, :open).group_by do |open_hours|
      { day: open_hours.day, month: open_hours.month }
    end
  end

  def active_nearbys(total_rooms)
    nearbys(total_rooms).try(:active) || []
  end

  def availability_on(date)
    RoomWithAvailability.
      new(room: self, date: Date.parse(date)).
      available_reservation_times
  end

  def available_on?(date)
    availability_on(date).count.positive?
  end

  def cover_photo(size = :medium)
    return "blank.jpg" unless photos.length.positive?

    photos.first.fitted(size)
  end

  def average_rating
    return 0 if guest_reviews.count.zero?

    guest_reviews.average(:star).round
  end

  def ready?
    approved? && photos.present? && open_hours_week_days.present?
  end

  def update_active_status
    update(active: false) unless ready?
  end

  private

  def accepted_payment_methods
    if payment_methods.empty?
      errors.add(:payment_methods, "must be specified")
    else
      payment_methods.each do |payment_method|
        unless ACCEPTED_PAYMENT_METHODS.include?(payment_method)
          errors.add(:payment_methods, "can't include '#{payment_method}'")
        end
      end
    end
  end

  def deactivate
    self.active = false
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room

  def show
    redirect_to root_path unless user_can_view_room

    @room = RoomWithAvailability.new(
      room: @room,
      date: params[:date].presence || Date.today,
    )
  end

  def availability
    room = RoomWithAvailability.new(
      room: @room,
      date: Date.parse(params[:date]),
    )

    render json: room.available_reservation_times
  end

  private

  def user_can_view_room
    @room.active? || current_user&.id == @room.user_id
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/suppliers/dashboard_controller.rb
module Suppliers
  class DashboardController < SuppliersController
    def index
      @rooms = current_user.rooms
    end
  end
end

app/controllers/suppliers/reservations_controller.rb
module Suppliers
  class ReservationsController < SuppliersController
    before_action :set_reservation, except: :index

    def index
      @reservations = current_user.rooms_reservations
    end

    def approve
      @reservation.approved!

      NotifyReservationApproval.call(@reservation)
      flash[:notice] = "Reservation created successfully!"

      redirect_to suppliers_reservations_path
    end

    def decline
      @reservation.declined!

      redirect_to suppliers_reservations_path
    end

    private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end
  end
end

app/controllers/suppliers/rooms_controller.rb
module Suppliers
  class RoomsController < SuppliersController
    skip_before_action :authorize_supplier, only: %i[new create]

    before_action :set_room, except: %i[index new create]
    before_action :authorize_user!, except: %i[index new create]

    def index
      @rooms = current_user.rooms
    end

    def new
      @room = current_user.rooms.build
    end

    def create
      @room = current_user.rooms.build(room_params)

      if @room.save
        redirect_to open_hours_suppliers_room_path(@room), notice: "Saved..."
      else
        flash[:alert] = @room.errors.full_messages.first

        render :new
      end
    end

    def update
      if @room.update(room_params)
        flash[:notice] = "Saved..."
      else
        flash[:alert] = @room.errors.full_messages.first
      end

      redirect_back(fallback_location: root_path)
    end

    def description; end

    def amenities; end

    def pricing; end

    def location; end

    def open_hours; end

    def photo_upload; end

    private

    def set_room
      @room = Room.find(params[:id])
    end

    def authorize_user!
      if current_user.id != @room.user_id
        redirect_to root_path, alert: "You don't have permission"
      end
    end

    def room_params
      params.
        require(:room).
        permit(
          :name, :address, :summary, :stations, :price, :active,
          :available_procedures, :open_hours, :practitioners, :has_lobby,
          :has_xrays, :has_heating, :has_internet, :appointment_duration,
          payment_methods: [], open_hours_week_days: [],
          open_hours_special_days: []
        )
    end
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_supplier

  private

  def authorize_supplier
    redirect_to root_path unless current_user.supplier?
  end
end

app/helpers/room_helper.rb
module RoomHelper
  def availability_options
    [["Available", 1], ["Not Available", 0]]
  end
end

app/views/suppliers/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Description", description_suppliers_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Services", amenities_suppliers_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_suppliers_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_suppliers_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Open Hours", open_hours_suppliers_room_path, class: "sidebar-link active" %>

    <span id="open_hours_check" class="pull-right text-babu"
          style="display: <%= @room.open_hours_week_days.empty? ? 'none' : 'initial' %>">
      <i class="fa fa-check"></i>
    </span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_suppliers_room_path, class: "sidebar-link active" %>

    <% unless @room.photos.empty? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>

<% if @room.approved? %>
  <%= form_for @room, url: suppliers_room_path do |f| %>
    <%= f.hidden_field :active, value: !@room.active? %>
    <%= f.submit "#{@room.active? ? 'Unpublish' : 'Publish' }",
                 id: "publish_button", class: "btn btn-normal btn-block", disabled: !@room.ready? %>
  <% end %>
  <div class="room__not-ready-text" id="not-ready-text" style="display: <%= @room.ready? ? "none" : "intial" %>;">
    * Please complete all sections to be able to publish your clinic.
  </div>
<% else %>
  <div class="room__approval-text">Waiting for approval</div>
<% end %>

app/views/suppliers/rooms/amenities.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">Services</div>

      <div class="panel-body">
        <div class="container">

          <%= form_for @room do |f| %>
            <div class="row form-group">
              <div class="col-md-3">
                <%= f.check_box :has_lobby %><%= f.label :has_lobby %>
              </div>
              <div class="col-md-3">
                <%= f.check_box :has_xrays %><%= f.label :has_xrays %>
              </div>
              <div class="col-md-3">
                <%= f.check_box :has_heating %><%= f.label :has_heating %>
              </div>
              <div class="col-md-3">
                <%= f.check_box :has_internet %><%= f.label :has_internet %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-4">
                <%= f.label :practitioners %>
                <%= f.number_field :practitioners, class: "form-control" %>
              </div>
              <div class="col-md-4">
                <%= f.label :stations %>
                <%= f.number_field :stations, class: "form-control" %>
              </div>
              <div class="col-md-4">
                <%= f.label :appointment_duration %>
                <div>
                  <%= f.time_select :appointment_duration, {},
                    { class: "form-control", style: "width: 45%; display: inline-block;" } %>
                </div>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.label :available_procedures %>
                <%= f.text_area :available_procedures, class: "form-control", rows: 5,
                    placeholder: "List all procedures available at your clinic." %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/suppliers/rooms/description.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">Description</div>

      <div class="panel-body">
        <div class="container">

          <%= form_for @room do |f| %>
            <div class="row">
              <div class="col-md-12 form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control", required: true,
                    placeholder: "What is your clinic name?" %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12 form-group">
                <%= f.label :name %>
                <%= f.text_area :summary, rows: 5, class: "form-control", required: true,
                    placeholder: "Describe your clinic, add any information you will like to share with your clients." %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12 form-group">
                <%= f.label :open_hours %>
                <%= f.text_area :open_hours, class: "form-control", rows: 5,
                    placeholder: "Provide your working hours, including open/close days." %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/suppliers/rooms/index.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">

        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag room.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%= room.name %></h4>
            </div>
            <div class="col-md-3 text-right">
              <%= link_to "Update", description_suppliers_room_path(room), class: "btn btn-form" %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/suppliers/rooms/location.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">Location</div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="col-md-12 form-group">
                <%= f.label :address %>
                <%= f.text_field :address, class: "form-control", required: true,
                    placeholder: "Type your location" %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  $(function() {
    $("#room_address").geocomplete();
  })
</script>

app/views/suppliers/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your beautiful Clinic
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @room do |f| %>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-8">
            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, class: "form-control", "data-behavior": "geocomplete",
                  placeholder: "Type your location" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :summary %>
              <%= f.text_area :summary, class: "form-control", rows: 5,
                  placeholder: "Describe your clinic, add any information you will like to share with your clients." %>
           </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :available_procedures %>
              <%= f.text_area :available_procedures, class: "form-control", rows: 5,
                  placeholder: "List all procedures available at your clinic." %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-3">
            <div class="form-group select">
              <%= f.label :has_lobby %>
              <%= f.select :has_lobby, availability_options, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group select">
              <%= f.label :has_xrays %>
              <%= f.select :has_xrays, availability_options, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group select">
              <%= f.label :has_heating %>
              <%= f.select :has_heating, availability_options, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group select">
              <%= f.label :has_internet %>
              <%= f.select :has_internet, availability_options, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <%= f.label :price %>
              <%= f.number_field :price, class: "form-control", step: 0.1 %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= f.label :practitioners %>
              <%= f.number_field :practitioners, class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= f.label :stations %>
              <%= f.number_field :stations, class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= f.label :appointment_duration %>
              <div>
                <%= f.time_select :appointment_duration, {},
                  { class: "form-control", style: "width: 45%; display: inline-block;" } %>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :payment_methods %>
              <%= f.select :payment_methods, Room::ACCEPTED_PAYMENT_METHODS,
                { class: "form-control", include_hidden: false }, { multiple: true, size: 5 } %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :open_hours %>
              <%= f.text_area :open_hours, class: "form-control", rows: 5,
                              placeholder: "Provide a summary for open hours, including open/close days." %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12 text-center">
            <%= f.submit "Create My Clinic", class: "btn btn-normal" %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/suppliers/rooms/open_hours.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Open Hours
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="open-hours"
               data-behavior="open-hours-week"
               data-url="<%= open_hours_week_days_path %>"
               data-room-id="<%= @room.id %>">

            <h4 class="open-hours__title">Week days</h4>
            <table class="open-hours__table">
              <tbody>
                <% @room.open_hours_by_week_day.each do |day, open_hours| %>
                  <tr data-behavior="open-hours-day">
                    <td><span class="open-hours-day"><%= day.capitalize %></span></td>
                    <td><span class="open-hours__link" data-behavior="open-hours-add">add</a></td>
                    <td data-behavior="open-hours-blocks" data-day="<%= day %>">
                      <% if open_hours.empty? %>
                        <div class="open-hours-block" data-behavior="open-hours-block">
                          <span class="open-hours-block__closed open-hours-block__closed--left"
                                data-behavior="open-hours-closed">Closed</span>
                        </div>
                      <% else %>
                        <% open_hours.each do |block| %>
                          <div class="open-hours-block"
                               data-behavior="open-hours-block"
                               data-id="<%= block.id %>">
                            <select class="open-hours__select"
                                    data-behavior="open-hours-time-open"
                                    data-value="<%= block.open&.strftime("%H:%M") %>"></select>
                            <select class="open-hours__select"
                                    data-behavior="open-hours-time-close"
                                    data-value="<%= block.close&.strftime("%H:%M") %>"></select>
                            <i class="fa fa-trash open-hours-block__delete"
                               aria-hidden="true"
                               data-behavior="open-hours-delete"></i>
                          </div>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="open-hours"
               data-behavior="open-hours-special"
               data-url="<%= open_hours_special_days_path %>"
               data-room-id="<%= @room.id %>">

            <h4 class="open-hours__title">
              Special days
              <span class="open-hours__link open-hours__link--right" data-behavior="open-hours-new">
                new
              </span>
            </h4>
            <table class="open-hours__table">
              <tbody data-behavior="open-hours-days">
                <% @room.open_hours_by_special_day.each do |day, open_hours| %>
                  <tr data-behavior="open-hours-day">
                    <td>
                      <div class="open-hours-day">
                        <select class="open-hours__select"
                                data-behavior="open-hours-date-month"
                                data-value="<%= day[:month] %>") %>"></select>
                        <select class="open-hours__select"
                                data-behavior="open-hours-date-day"
                                data-value="<%= day[:day] %>") %>"></select>
                      </div>
                    </td>
                    <td><span class="open-hours__link" data-behavior="open-hours-add">add</a></td>
                    <td data-behavior="open-hours-blocks">
                      <% open_hours.each do |block| %>
                        <div class="open-hours-block"
                             data-behavior="open-hours-block"
                             data-id="<%= block.id %>">

                          <% if block.closed? %>
                            <span class="open-hours-block__closed"
                                  data-behavior="open-hours-closed">Closed</span>
                          <% else %>
                            <select class="open-hours__select"
                                    data-behavior="open-hours-time-open"
                                    data-value="<%= block.open&.strftime("%H:%M") %>"></select>
                            <select class="open-hours__select"
                                    data-behavior="open-hours-time-close"
                                    data-value="<%= block.close&.strftime("%H:%M") %>"></select>
                          <% end %>

                          <i class="fa fa-trash open-hours-block__delete"
                             aria-hidden="true"
                             data-behavior="open-hours-delete"></i>
                        </div>
                      <% end %>

                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/suppliers/rooms/photo_upload.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list', photos: @room.photos %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/suppliers/rooms/pricing.html.erb
<%= render "shared/suppliers_navbar" %>

<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">Pricing</div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="col-md-6 form-group">
                <%= f.label :price %>
                <%= f.number_field :price, class: "form-control", required: true, step: 0.1 %>
              </div>
              <div class="col-md-6 form-group">
                <%= f.label :payment_methods %>
                <%= f.select :payment_methods, Room::ACCEPTED_PAYMENT_METHODS,
                  { class: "form-control", include_hidden: false }, { multiple: true, size: 5 } %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>